### ISSUE TITLE
Error effect_setval_inline: invalid param

### ISSUE THREAD

**Issue by Smoolak** [norihiro/obs-color-monitor#14]
Hi,

I compiled this on Arch Linux and I was able to make the waveform work in obs. However, when I try to use the histogram or the vectorscope, I get the following error in the terminal and the source remain transparant or black:

`error: effect_setval_inline: invalid param`

**Comment by norihiro** [comment]
Hi @Smoolak,
Could you upload the log file and share a link?
In `Help` / `Log Files` menu, you can upload current or last log file.

I'm suspecting effect file is not correctly loaded.
If that's the case, you will see `Cannot load a message like `*/waveform.effect'` in a log.
Waveform can fallback to use defalut effect built in OBS-Studio but intensity and display-mode won't work. And, other sources cannot fallback.

**Comment by norihiro** [comment]
Closed due to inactivity for a while.
