### ISSUE TITLE
[Feature request] Graduation scale for the Waveform monitor

### ISSUE THREAD

**Issue by cramaboule** [norihiro/obs-color-monitor#2]
**Describe the solution you'd like**
Graduation scale from 0 to 100% (step 10%) for the waveform monitor such as https://static.bhphotovideo.com/explora/explora/sites/default/files/not-clipped.jpg

**Additional information**
https://static.bhphotovideo.com/explora/explora/sites/default/files/not-clipped.jpg

**Comment by norihiro** [comment]
Thank you for your feature request.
The feature is implemented in 0.1.5.

**Comment by cramaboule** [comment]
Thanks a lot !! works great
