### ISSUE TITLE
[Feature request] add skin tone line on vectorscope 

### ISSUE THREAD

**Issue by cramaboule** [norihiro/obs-color-monitor#3]
**Describe the solution you'd like**
Hi Norihiro,
Could you add the skin tone line on the vectorscope. 

**Additional information**
https://images.app.goo.gl/mEni53irsA5jM6EUA

**Comment by norihiro** [comment]
Do you have any idea where is the right angle of the skin tone line?
I'm surveying but have not found a reliable source.
It might depend tools; some tools show lines at around 32 to 34 degrees from the North. 
I also asked on [Stack Exchange](https://video.stackexchange.com/questions/33785/angle-of-skin-tone-line-on-vectorscope)
but I didn't have answer.

**Comment by cramaboule** [comment]
What if we think the way around? 
What is the color reference for skin color? 
Like: https://www.color-hex.com/color-palette/29434

**Comment by cramaboule** [comment]
Hi again,
from the colorchecker manual p13 : https://www.xrite.com/-/media/xrite/files/manuals_and_userguides/c/o/colorcheckerpassport_user_manual_en.pdf
color 1 and 2 are skin tone on my file: https://www.cramaboule.com/download.php?file=pictures.zip
I made a colorchecker bmp file.
So you can check.

It seems that on DaVinci Resolve it is 34°
https://blog.frame.io/2020/10/05/skin-tones-in-davinci-resolve/

**Comment by norihiro** [comment]
Hi cramaboule,
Thank you for your survey. I also checked some sources.

Commercial tools:
- 33° at Final Cut Pro, BT.709.
- 34° at Premier Pro, BT.709.
- 32° at Pinnacle Studio, BT.709.
- 34° at DaVinci Resolve, BT.709 #issuecomment-841281490_

Color references:
- 35° and 39° from Xrite color checker
- 46° average, 32°-55°
- 37° average, 19°-47° from Pantone SP

Color references look a little biased to yellow. I think around 33° (#CBAB99 for example) is the reasonable angle and it's consistent among the industry.

**Comment by norihiro** [comment]
[0.1.6](https://github.com/norihiro/obs-color-monitor/releases/tag/0.1.6) is released.
