### ISSUE TITLE
Clean or order source input

### ISSUE THREAD

**Issue by cramaboule** [norihiro/obs-color-monitor#4]
**Describe the bug**
When adding source input, all sources and scenes are totally mixed.
Could you make order like scenes first and sources second or by alphabetical order or something? 
I have a very long list of stuff difficult sometimes to find my source :-)

**Comment by norihiro** [comment]
Currently scenes are first. Then, other sources follow.
Inside the scenes and sources, I agree it should be ordered, maybe alphabetical.
Btw, how urgent you want to have the fixed version?

**Comment by cramaboule** [comment]
Yes perhaps alphabetical order inside scenes and sources would be great. 
I think it is not urgent.

**Comment by norihiro** [comment]
[0.1.6](https://github.com/norihiro/obs-color-monitor/releases/tag/0.1.6) is released.
