### ISSUE TITLE
Add Focus Peaking

### ISSUE THREAD

**Issue by norihiro** [norihiro/obs-color-monitor#49]
https://obsproject.com/forum/threads/obs-color-monitor.143375/post-560102

**Comment by eanderson143** [comment]
+1 for focus peaking

Given how color/light focused this plugin is, maybe a seperate more lightweight plugin would be more realistic? Just a thought. We all appreciate the support you give to these plugins!

**Comment by eanderson143** [comment]
Awesome! Can't wait for the release to try it out!
