### ISSUE TITLE
Not showing anything in OBS after install

### ISSUE THREAD

**Issue by roirobo** [norihiro/obs-color-monitor#52]
I have downloaded and installed the .deb package but Dock is not showing neither on Tools or Add Source menu items.

Logs: https://obsproject.com/logs/Y9o8glGzEs-qb74h

**Comment by norihiro** [comment]
The log shows version string `OBS 1:27.0.1-dmo2`, which looks not the official version.
You might need to adjust the install location.

The deb package of this plugin is installing binary to `/usr/lib/obs-plugins/obs-color-monitor.so` and data to `/usr/share/obs/obs-plugins/obs-color-monitor/`. Both files should be placed to the right location for your OBS studio.

For example,
```
sudo ln -s /usr/lib/obs-plugins/obs-color-monitor.so /usr/lib/x86_64-linux-gnu/obs-plugins/
```

**Comment by norihiro** [comment]
Probably, the [the latest version](https://github.com/norihiro/obs-color-monitor/releases/tag/0.6.1) should work because the build script was rewritten based on the new plugin-template. Please feel free to reopen this ticket if you still have the issue.
