### ISSUE TITLE
A linux zip file and not a deb

### ISSUE THREAD

**Issue by Desaydrone** [norihiro/obs-color-monitor#65]
Hello,

I'm on fedora 37 and i'd like to install this plugin without compil it, but the only linux version is a deb package, is it possible to have a zip version instead ??

Thanks for your works !!

**Comment by norihiro** [comment]
Which package of obs-studio have you installed, RPM Fusion, Flathub, or something else?

**Comment by Desaydrone** [comment]
Hello,

I install the RPM Fusion one.

It seems to work with unzip the file.
I put the obs-color-monitor.so in /usr/lib64/obs-plugins

And the obs-color-monitor folder in /usr/share/obs/obs-plugins

Thanks for the suggestion !!

**Comment by norihiro** [comment]
I've created RPM packages for Fedora 36 and 37. I was actually thinking that idea for a long time but have never started to make it. I'd like to thank you for remind me about that.

https://github.com/norihiro/obs-color-monitor/releases/tag/0.4.4
