### ISSUE TITLE
Version Mismatch?

### ISSUE THREAD

**Issue by rafajafar** [norihiro/obs-color-monitor#91]
I think there's a version mismatch between the RC7 and what's passed to OBS. I used StreamUp and it's getting confused. Out of a few dozen, it's just yours and one other. Thank you very much for your continued support on this plugin!
![Screenshot 2024-07-20 164006](https://github.com/user-attachments/assets/85d0ddc5-cd90-4ab7-bf0c-77642f94f934)

**Comment by norihiro** [comment]
The latest version is 0.7.0.
I think the dialog is poped-up by a 3rd party plugin. Could you ask for the author of SteamUP?
