### ISSUE TITLE
OBS 30.1.2 on Debian: possible import conflicts

### ISSUE THREAD

**Issue by eribertomota** [norihiro/obs-color-monitor#93]
**Describe the bug**

Dear @norihiro,

I am the color-monitor maintainer on Debian. The version 0.7.0 builds fine, but it doesn't load. The following message is shown:

`warning: Skipping module '/usr//lib/x86_64-linux-gnu/obs-plugins/color-monitor.so' due to possible import conflicts`

Currently, obs-studio is being built on Debian with Qt6, but your plugin only accepts Qt5. I think this is the problem. The Exeldro's plugins accept Qt5 and Qt6 and I have no problems with them.

**Your setup**
- Settings of the source to reproduce the bug: described above.
- OS and OBS-Studio version: Debian Sid (unstable) and OBS 30.1.2.
- Version of the plugin: 0.7.0.

Regards,

Eriberto

**Comment by norihiro** [comment]
Thank you for maintaining the package.

You need to add `-D QT_VERSION=6` to select Qt6.

Probably, I should add `option` command to set `6` as the default but I'm not familiar enough on CMake. Suggestion would be welcome.

**Comment by eribertomota** [comment]
> Thank you for maintaining the package.
> 
> You need to add `-D QT_VERSION=6` to the `cmake` command so that it will select Qt6.

Thanks! It worked fine.

> 
> Probably, I should add `option` command to set `6` as the default but I'm not familiar enough on CMake. Suggestion would be welcome.

I am better with autotools and I am also not familiar with CMake. The following plugins, already in Debian, use qt6: advanced-scene-switcher, obs-downstream-keyer, obs-scene-collection-manager, obs-scene-notes-dock, obs-source-copy and obs-transition-table.
